# Let NetworkManager manage all devices on this system
network:
  version: 2
  renderer: NetworkManager
  ethernets:
          eno1:
                dhcp4: no
                addresses:
                         - 192.168.2.1/24
                gateway4: 192.168.2.1
                nameservers:
                        addresses: [192.168.2.1, 8.8.8.8]
